#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
DO
\$do\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '$APP_DB_USER') THEN
        CREATE USER $APP_DB_USER WITH PASSWORD '$APP_DB_PASSWORD';
    END IF;
END
\$do\$;

CREATE SCHEMA IF NOT EXISTS app AUTHORIZATION $APP_DB_USER;

DO
\$do\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '$DATA_DB_USER') THEN
        CREATE USER $DATA_DB_USER WITH PASSWORD '$DATA_DB_PASSWORD';
    END IF;
END
\$do\$;

CREATE SCHEMA IF NOT EXISTS data AUTHORIZATION $DATA_DB_USER;

DO
\$do\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '$KEYCLOAK_DB_USER') THEN
        CREATE USER $KEYCLOAK_DB_USER WITH ENCRYPTED PASSWORD '$KEYCLOAK_DB_PASSWORD';
    END IF;
END
\$do\$;

CREATE DATABASE $KEYCLOAK_DB;
GRANT ALL PRIVILEGES ON DATABASE $KEYCLOAK_DB TO $KEYCLOAK_DB_USER;

\c $KEYCLOAK_DB;
GRANT ALL ON SCHEMA public TO $KEYCLOAK_DB_USER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $KEYCLOAK_DB_USER;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO $KEYCLOAK_DB_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $KEYCLOAK_DB_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO $KEYCLOAK_DB_USER;
EOSQL
